SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT LIKE 'A%'
    AND CITY NOT LIKE 'E%'
    AND CITY NOT LIKE 'I%'
    AND CITY NOT LIKE 'O%'
    AND CITY NOT LIKE 'U%';

/* Theory */

// Alternative Approach Using RegEx

SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT REGEXP '^[AEIOUaeiou]';

// Alternative Approach For Case Insensitive;

SELECT DISTINCT CITY
FROM STATION
WHERE UPPER(CITY) NOT LIKE 'A%'
  AND UPPER(CITY) NOT LIKE 'E%'
  AND UPPER(CITY) NOT LIKE 'I%'
  AND UPPER(CITY) NOT LIKE 'O%'
  AND UPPER(CITY) NOT LIKE 'U%';

